### ISSUE TITLE
Feature request: provide payment data fields

### ISSUE THREAD

**Issue by learntheropes** [Peach2Peach/peach-api-ts#2]
This was mentioned already on telegram, but I leave it also here as a memo.

Currently, the payment data fields for each payment method are only available at the bottom of the docs, under `PaymentMethod` data types.

This requires to manually check for updates every few days and update the own code every time you add a payment method.

It would be great if you could return the same info also in the `/info` endpoint, so that API users can update their UI dynamically.

**Comment by Czino** [comment]
Yes, we are going to let the server be the source of truth for payment data fields for publishing and validating counterparty payment data.

Idea is to provide following the structure:

Example
```
{
  "paypal": {
    "mandatory": [
      [["userName"], ["email"], ["phone"]]
    ],
    "optional": ["reference"]
  },
  "sepa": {
    "mandatory": [
      [["beneficiary"]],
      [["iban"]],
      [["bic"]]
    ],
    "optional": ["reference"]
  },
  "nationalTransfer": {
    "mandatory": [
      [["beneficiary"]],
      [["iban", "bic"], ["accountNumber"]]
    ],
    "optional": ["reference"]
  }
}
```

The difficulty is communicating which fields are exactly required as in some cases, it can be either or.

So following the example structure, the fields could be expressed as following logical operators:
- `paypal`: `userName || email || phone`
- `sepa`: `beneficiary && iban && bic`
- `nationalTransfer`: `beneficiary && ((iban && bic) || accountNumber)`

**Comment by Czino** [comment]
Yes, we had discussed this option internally but there's 2 downsides to this approach:

1. duplication
2. we were looking for a way to logically show groups of fields that belong together. In this case `iban` and `bic` as a group in opposition to `accountNumber`

**Comment by learntheropes** [comment]
It took me some time to completely understand your logic.

Now that I understand it, it's much more detailed than my proposal. 

Basically, every array or array is mandatory, inside that, you can choose the array you prefer.

My proposal requires more work on our side. I.e. if an element is in every array, it is “really” mandatory, otherwise provide all the remaining fields in one of the arrays.

**Comment by Czino** [comment]
Hi we now offer a new endpoint to request payment data fields: https://docs.peachbitcoin.com/#payment-method-info

Also added an API method to the ts-wrapper
